import "Model\Color.idl";
import "Model\Value.idl";

namespace Mooville.QUno.Model
{
    [default_interface]
    runtimeclass Card
    {
        Card();
        Card(Mooville.QUno.Model.Color c, Mooville.QUno.Model.Value v);
        Mooville.QUno.Model.Color Color;
        Mooville.QUno.Model.Value Value;
    }
}
