import "Model\Hand.idl";

namespace Mooville.QUno.Model
{
	[default_interface]
	runtimeclass Player
	{
		Player();
		String Name;
		Boolean IsHuman;
		Mooville.QUno.Model.Hand Hand{ get; };
		Mooville.QUno.Model.Card ChooseCardToPlay();
		Mooville.QUno.Model.Color ChooseWildColor();
	};
}
