// QUnoComponent - Value.idl
// 2021 Roger Deetz

namespace Mooville.QUno.Model
{
    enum Value
    {
        Wild,
        WildDrawFour,
        DrawTwo,
        Reverse,
        Skip,
        Zero,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
    };
}
