// QUnoReunion - MainWindow.idl
// 2021 Roger Deetz

namespace Mooville.QUno.Reunion
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }
}
